import { CSSProperties } from 'react';
import { colors } from './colors';

export const s: Record<string, CSSProperties> = {
  authWrap: {
    minHeight: '100vh',
    background: colors.background,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  authBox: {
    background: colors.white,
    borderRadius: 16,
    border: `1.5px solid ${colors.border}`,
    padding: 32,
    width: '100%',
    maxWidth: 400,
  },
  label: {
    display: 'block',
    fontSize: 14,
    fontWeight: 600,
    color: colors.text,
    marginBottom: 6,
  },
  input: {
    display: 'block',
    width: '100%',
    border: `1.5px solid ${colors.border}`,
    borderRadius: 10,
    padding: '12px 14px',
    fontSize: 16,
    color: colors.text,
    background: colors.white,
  },
  btn: {
    background: colors.primary,
    color: colors.white,
    borderRadius: 10,
    padding: '14px 20px',
    fontSize: 16,
    fontWeight: 700,
    border: 'none',
    cursor: 'pointer',
    textAlign: 'center' as const,
  },
  btnOutline: {
    background: 'transparent',
    color: colors.textLight,
    borderRadius: 10,
    padding: '13px 20px',
    fontSize: 16,
    fontWeight: 600,
    border: `1.5px solid ${colors.border}`,
    cursor: 'pointer',
  },
  btnDanger: {
    background: 'transparent',
    color: '#e53e3e',
    borderRadius: 10,
    padding: '13px 20px',
    fontSize: 16,
    fontWeight: 600,
    border: '1.5px solid #e53e3e',
    cursor: 'pointer',
  },
  linkBtn: {
    background: 'none',
    border: 'none',
    color: colors.primary,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    padding: 0,
  },
  card: {
    background: colors.white,
    borderRadius: 12,
    border: `1.5px solid ${colors.border}`,
    padding: 16,
    marginBottom: 12,
  },
  errorMsg: {
    color: colors.error,
    fontSize: 13,
    marginTop: 8,
  },
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    zIndex: 200,
    padding: 16,
  },
  modal: {
    background: colors.white,
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 480,
    maxHeight: '90vh',
    overflowY: 'auto' as const,
  },
  sectionHeader: {
    fontSize: 12,
    fontWeight: 700,
    color: colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.8px',
    marginBottom: 10,
    marginTop: 4,
  },
  chip: {
    padding: '6px 14px',
    borderRadius: 20,
    border: `1.5px solid ${colors.border}`,
    background: colors.white,
    fontSize: 13,
    fontWeight: 600,
    color: colors.textLight,
    cursor: 'pointer',
    flexShrink: 0,
  },
  chipActive: {
    padding: '6px 14px',
    borderRadius: 20,
    border: `1.5px solid ${colors.primary}`,
    background: colors.primary,
    fontSize: 13,
    fontWeight: 600,
    color: colors.white,
    cursor: 'pointer',
    flexShrink: 0,
  },
  reasonBadge: {
    padding: '4px 10px',
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 600,
    color: colors.text,
    whiteSpace: 'nowrap' as const,
  },
};
